task/task/urls.py
from django.contrib import admin
from django.urls import path,include
# from taskapp import views

urlpatterns = [
    path('',include('taskapp.urls')),
    path('admin/', admin.site.urls),
]

task/taskapp/urls.py
from django.urls import path
from taskapp import views
app_name="taskapp"

urlpatterns=[
    path('',views.index,name='index'),
    path('home/',views.home,name='home'),
    path('login/',views.user_login,name='user_login'),
    path('register/',views.register,name='register'),
    path('user_logout/',views.user_logout,name='user_logout'),
    path('ask/', views.ask_question, name='ask_question'),
    path('answer/<int:question_id>/', views.answer_question, name='answer'),
    path('answer/like/', views.like_answer, name='like_answer'),
]  

# <int:question_id>/              like/<int:answer_id>/

task/taskapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

class userprofile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

task/taskapp/forms.py
from django import forms
from django.contrib.auth.models import User
from taskapp.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'content']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']

class user_form(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username','email','password')                                #'__all__'

# class user_profileform(forms.ModelForm):
#     class Meta:
#         model = userprofile
#         fields = ('user_img','user_url')

task/taskapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import QuestionForm, AnswerForm, user_form
from .models import Question, Answer, Like
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout

# Create your views here.
# def base(request):
#     return render(request,'base.html')

# def home(request):
#     return render(request,'home.html')

def index(request):
    return render(request,'index.html')


def home(request):
    questions = Question.objects.all()
    return render(request, 'home.html', {'questions': questions})


def ask_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.user = request.user
            question.save()
            return redirect('taskapp:home')
    else:
        form = QuestionForm()
    return render(request, 'ask_questions.html', {'form': form})


def answer_question(request, question_id):
    question = Question.objects.get(id=question_id)

    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.user = request.user
            answer.question = question
            answer.save()
            return redirect('answer_question', question_id=question.id)
    else:
        form = AnswerForm()
    return render(request, 'answer_question.html', {'form': form, 'question': question})


def like_answer(request, answer_id):
    answer = Answer.objects.get(id=answer_id)
    like, created = Like.objects.get_or_create(user=request.user, answer=answer)

    if not created:
        like.delete()

    return redirect('answer_question', question_id=answer.question.id)

def register(request):
    register = False
    if request.method =='POST':
        userform = user_form(request.POST)

        if userform.is_valid():
           user = userform.save()
           user.set_password(user.password)
           user.save()

           register = True
    else:
        userform = user_form()
    return render(request,'registration.html',{'userform':userform,'register':register})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('taskapp:home'))
            else:
                return HttpResponse("<h1>User is not active</h1> ")
        else:
            return HttpResponse("<h1>Invalid creds</h1>")
    return render(request,'login.html')

# def user_login(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
        
#         user = authenticate(request,username=username,password=password)
#         if user:
#             # if user.is_active:
#             login(request,user)
#             return redirect(request.GET.get('next', '/'))
#                 # return HttpResponseRedirect(reverse('taskapp:base'))
#         else:
#             error_message = 'Invalid username or password.'
#             return render(request, 'login.html', {'error_message': error_message})
#                 # return HttpResponse("<h1>User is not active</h1> ")
#     else:
#         return render(request, 'login.html')
#             # return HttpResponse("<h1>Invalid credentials</h1>")
#     # return render(request,'login.html')
# @login_required


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('taskapp:home'))

task/templates/answer_question.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Answer Question</h1>
    <h3>{{ question.id }}</h3>
    <h3>{{ question.title }}</h3>
    <p>{{ question.content }}</p>
    
    <form method="POST" action="">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

task/templates/ask_questions.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Ask a Question</h1>
    
    <form method="POST" action="">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

task/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>Quora..</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body>

  <nav class="navbar navbar-dark bg-dark">
    <div class="container">
        <ul class="nav navbar">
            <li class="nav-item"><a class="nav-link" href="{% url 'taskapp:home' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'taskapp:register' %}">Register</a></li>
            {% if user.is_authenticated %}                
                <li class="nav-item"><a class="nav-link" href="{% url 'taskapp:ask_question' %}">Ask Questions</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'taskapp:answer' pk=question_id %}">Answer Questions</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'taskapp:user_login' %}">Login</a></li> 
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'taskapp:user_logout' %}">Logout</a></li> 
                {% comment %} {% if user.is_authenticated %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'taskapp:ask_question' %}">Ask Questions</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'taskapp:answer_question' %}">Answer Questions</a></li>
                {% endif %} {% endcomment %}
            {% endif %}
        </ul>
    </div>
    <div>
        {% if user.is_authenticated %}
            <p>Welcome{{ user.username }}</p>
        {%  endif %}
    </div>
</nav>
{% block content %}

{% endblock %}

</body>
</html>
{% comment %} {% if user.is_authenticated %}
<p>Welcome, {{ user.username }}! <a href="{% url 'taskapp:user_logout' %}">Logout</a></p>
{% else %}
<p><a href="{% url 'taskapp:user_login' %}">Login</a></p>
{% endif %}

{% block content %}
{% endblock %} {% endcomment %}

task/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1 align="center">Quora</h1>
  <br><br>
  <h2>Questions</h2>
  <ul>
    {% for question in questions %}
      <li>
        <h3>{{ question.title }}</h3>
        <p>{{ question.content }}</p>
        <p>Asked by: {{ question.user.username }}</p>
        <a href="{% url 'taskapp:answer' %}">Answer</a>
      </li>
    {% empty %}
      <p>No questions available.</p>
    {% endfor %}
  </ul>
  <a href="{% url 'taskapp:ask_question' %}">Ask a Question</a>
{% endblock %}

{% comment %} {% extends 'base.html' %}

{% block content %}
<h1>Welcome.....</h1>
{% endblock %} {% endcomment %}

task/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome.....</h1>
{% endblock %}

{% comment %} {% extends 'base.html' %}

{% block content %}
  <h1>Quora</h1>
  
  <h2>Questions</h2>
  <ul>
    {% for question in questions %}
      <li>
        <h3>{{ question.title }}</h3>
        <p>{{ question.content }}</p>
        <p>Asked by: {{ question.user.username }}</p>
        <a href="{% url 'answer_question' question_id=question.id %}">Answer</a>
      </li>
    {% empty %}
      <p>No questions available.</p>
    {% endfor %}
  </ul>
  <a href="{% url 'taskapp:ask_question' %}">Ask a Question</a>
{% endblock %} {% endcomment %}

task/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Login here.....!!</h1>
        {% if error_message %}
            <p>{{ error_message }}</p>
        {% endif %}
        {% if login %}
                <h1>Welcome</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{ QuestionForm.as_p }}
                    {{ AnswerForm.as_p }}
                    <input type="submit" class="btn btn-primary" value="send">
                </form>
        {% else %}
            <form action="{% url 'taskapp:user_login' %}" method="POST">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" id="username" name="username"><br><br>
                <label for="password">Password:</label>
                <input type="password" id="password" name="password"><br>
                <input type="submit" class="btn btn-primary" value="login">
            {% comment %} <button type="submit">Login</button> {% endcomment %}
            </form>
            {% comment %} <form action="{% url 'taskapp:user_login' %}" method="POST">
                {% csrf_token %}
                <label for="username">Username :</label>
                <input type="text" name="username"><br><br>
                <label for="password">Password :</label>
                <input type="password" name="password"><br><br>
                <input type="submit" class="btn btn-success" value="login">
            </form> {% endcomment %}
        {% endif %}
    </div>
</div>
{% endblock %}

task/templates/registration.html
{%extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        {% if register %}
            <h1>Thank You for Registeration.....!!!!!</h1>
        {% else %}
            <h1>Registeration form.....!!!!!</h1>
            <form method="POST">
                {% csrf_token %}
                {{ userform.as_p }}
                {{ profileform.as_p }}
                <input type="submit" class="btn btn-primary" value="register">
            </form>
        {% endif %}
    </div>
</div>

{% endblock %}